user.name = "Danver Braganza"
user.email = "danver@imbue.com"

[git]
auto-local-bookmark = true

[ui]
ignore-files = [".gitignore", "~/.gitignore"]

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@"]
tug- = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
mine = ["bookmark", "list", "-r", "mine()"]
decs = ["desc"]
pre-commit = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  "jj diff -r @ --name-only --no-pager | xargs uv run pre-commit run --files"
]
pre-push = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  "jj diff --from main --to @ --name-only --no-pager | xargs uv run pre-commit run --hook-stage pre-push --files"
]
