user.name = "Danver Braganza"
user.email = "danverbraganza@gmail.com"

[git]
auto-local-branch = true

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@"]
tug- = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
